version: '1.27.3'

services:

  mywebsiteencrypt-nginx-container:
    container_name: 'mywebsiteencrypt-nginx-container'
    image: nginx:1.14.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./mywebsiteencrypt-site:/usr/share/nginx/html
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge